spring.application.name=AdventureXP

spring.web.resources.static-locations=classpath:/static/,classpath:/template/

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

app.auth.employee-one.first-name=Anna
app.auth.employee-one.username=anna
app.auth.employee-two.first-name=Mads
app.auth.employee-two.username=mads
